config/routes.rb
Rails.application.routes.draw do
  
  get 'questions/index'
  get 'questions/test'
  get "quizzes/home" => 'quizzes#home'
  get 'quizzes/new'
  get 'sesions/new'
  get 'sesions/logout'
  

  get "log_in" => "sesions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  root "quizzes#index"

resources :questions
  resources :users
  resources :sesions
  resources :quizzes

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
belongs_to :user
  validates_presence_of :title, :on => :create
  validates_presence_of :category
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :quizzes
   attr_accessor :password
  before_save :encrypt_password


  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

def self.authenticate(email, password)
  user = find_by_email(email)
  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
  else
    nil
  end
end

    def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #include SessionsHelper 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  layout 'temp'
  #@id => params[:qid]
  @score = 0
  def index
  	@question = Question.new
  end

  def test
  end

  def create
  	 @question = Question.new(questions_params)
  	if @question.save
  		redirect_to url_for(:action => :index, :id => params[:id])
  	else
  		render "new"
  	end
  end
  def score
  	
  	if params [:op1] == '1'
  		@score = 1
  	else
  		@score  = 0
  	end

  end

    private

  def questions_params
  	#:quiz_id => @id
  	params.require(:question).permit(:quiz_id, :quest, :op_1, :op_2, :op_3, :answer)
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  layout 'temp'
  before_action :find_user
	#@dami = sessions[:user_id]
  def index
  end
  
  def new
  	@quiz = Quiz.new
  end
	
  def show
  		#@dami = sessions[:user_id]
  		#@quizs = Quiz.where(user_id: @dami)
  		@quiz = @user.quizzes
  end


  def create
  	  	@quiz = Quiz.new(quiz_params)
  	if @quiz.save
  		redirect_to url_for(:controller => :questions, :action => :index, :qid => @quiz.id)
  	end
  end

  def home
    
  end

 
  def destroy
    @quiz = Quiz.find(params[:id]).destroy
    redirect_to(:controller => :quizzes, :action => :home)
  end

  def quest
  end


    private

  def quiz_params

  	params.require(:quiz).permit(:user_id, :title, :category)
  end

  def find_user
  
  	if session[:user_id]
  		@user = User.find session[:user_id]
  	end
  end
end

app/controllers/sesions_controller.rb
class SesionsController < ApplicationController
  layout 'temp'

  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      session[:email] = user.email
      redirect_to url_for(:controller => :quizzes, :action => :home), :notice => "Logged in user #{session[:email]}!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def logout
  	session[:user_id] = nil
  	session[:email] = nil
  	redirect_to(:action => "new")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	layout 'temp'
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to url_for(:controller => :sesions, :action => :new)
  	else
  		render "new"
  	end
  end



  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/temp.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>.:The Quiz Hub:.</title>


<%= stylesheet_link_tag('application', :media => 'all')%>
  	
</head>
<body>

	<header>
		<div id ="title">The QuizHub</div>
	</header>


<div id = "hd1"></div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

<%= yield %>

<div id= "footer">&copy; Damilola and Dewunmi</div>



</body>
</html>

app/views/questions/index.html.erb
<div id = "ball">
<h4>Your Quiz has being created, Pls fill the form,<br/>  to add questions to the quiz.</h4>

 <p>Click <%= link_to('here',{controller: 'questions', action: 'index'})%> to add another question, or <%= link_to('here',{controller: 'quizzes', action: 'home'})%> to go back</p>

   <%= form_for(@question) do |f| %>
           <div class="form-group">
           <label for="comments">Questions</label>
    		<div class="row">
    			<div class="col-xs-3">
    			 <%= f.text_area :quest, placeholder: 'Question' %>
    			</div>
			</div>
        </div>


		<div class="form-group">
		<label for="inputEmail">Option1</label>
        <div class="row">
           <div class="col-xs-3">
            	 <%= f.text_field :op_1, placeholder: 'Option1' %>
            </div>
        </div>
	</div>

			<div class="form-group">
			<label for="inputEmail">Option2</label>
        <div class="row">
           <div class="col-xs-3">
            	<%= f.text_field :op_2, placeholder: 'Option2' %>
            </div>
        </div>
	</div>


		<div class="form-group">
		<label for="inputEmail">Option3</label>
        <div class="row">
           <div class="col-xs-3">
            	<%= f.text_field :op_3, placeholder: 'Option3' %>
            </div>
        </div>
	</div>


			<div class="form-group">
			<label for="inputEmail">Answer</label>
        <div class="row">
           <div class="col-xs-3">
           <%= f.text_field :answer, placeholder: 'Answer' %>
            </div>
        </div>
	</div>

	<%= f.hidden_field :quiz_id, value: params[:qid] %>


        <button type="submit" class="btn btn-primary">Submit</button>

       
        <%end%>

</div>

app/views/questions/test.html.erb
<h3>Take Your Test</h3>

<% @question = Question.where(quiz_id: params[:id]) %>


    

    <div class="testTable">
    <div class="CSSTableGenerator" >
        <table>
            <tr>
                <td>Question</td><td>Option1</td><td>Option2</td><td>Option3</td><td>Option4</td>
            </tr>
            <% @question.each do |p| %>
    <tr>
      <td><%= p.quest %></td>
      <td><%= radio_button_tag 'op1', 0%><%= p.op_1 %></td>
      <td><%= radio_button_tag 'op1', 0%><%= p.op_2 %></td>
      <td><%= radio_button_tag 'op1', 0%><%= p.op_3 %></td>
      <td><%= radio_button_tag 'op1', 1%><%= p.answer %></td>
    </tr>

    <% end %>

        </table>
    </div>
</div>
<%= text_field_tag :score, params[@score]%>
<div id="btnmy"><button type="submit" class="btn btn-primary">Submit</button></div>

app/views/quizzes/home.html.erb
<!-- <div id = "logo">The Quiz Hub</div> -->
<!-- <div id = "crt"><a href="#" class="btn btn-large btn-success">Create  Quiz</a></div> -->
<% @quizzes = Quiz.where(user_id: session[:user_id]) %>
<%= link_to('Create Quiz',{controller: 'quizzes', action: 'new'}, class: "btn btn-large btn-success", id: "crt")%>

<%= link_to('Logout', {controller: 'sesions', action: 'logout'}, class: "btn btn-danger", id: "lg")%>

<!-- <div id = "lg"><a href="<" class="btn btn-danger">Logout</a></div>  -->
<div id = "logo">The QuizHub</div>
<div id = "head">
	<p><%= "Welcome User #{session[:email]} "%></p>
	<p>Your quizzes include the following:</p>
</div>



 </div>  

 <div class="testTable">
    <div class="CSSTableGenerator" >
        <table >
            <tr>
                <td>Quiz Title</td><td>Category</td><td>Created at</td><td>Actions</td>
            </tr>
            <% @quizzes.each do |p| %>
    <tr>
      <td><%= p.title %></td>
      <td><%= p.category %></td>
      <td><%= p.created_at %></td>
      <td>
        <%= link_to("Edit", p, :action => 'edit', :class => 'action edit') %>
        <%= link_to("Delete", p, :action => 'delete', :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
        </table>
    </div>
</div>

app/views/quizzes/index.html.erb
<!--<h1>FirstPage#first_page</h1>
<p>Find me in app/views/first_page/first_page.html.erb</p>!-->
<!-- <div id = "login"><a href="#" class="btn btn-danger">Log-in</a></div>  -->
<% @quizzes = Quiz.all %>
<%= link_to('Log-in',{controller: 'sesions', action: 'new'}, id: "homepage" )%>
<div id= "pipe">|</div>
<%= link_to('Sign up',{controller: 'users', action: 'new'}, id: "homepage" )%><br />

<div id ="blue"></div>

<!-- <table id= "testTable">
	<tr>
		<th>Quiz Title</th>
		<th>Category</th>
		<th><th>
	</tr>
</table> -->
<div class="testTable">
    <div class="CSSTableGenerator" >
        <table>
            <tr>
                <td>Quiz Title</td><td>Category</td><td>Take test</td>
            </tr>
            <% @quizzes.each do |p| %>
    <tr>
      <td><%= p.title %></td>
      <td><%= p.category %></td>

      <td><%=link_to('Take Test',{controller: 'questions', action: 'test', :id => p.id} ) %></td>

      <td></td>

    </tr>
    <% end %>
        </table>
    </div>
</div>
        

             
                   

app/views/quizzes/new.html.erb
<!-- <h1>Quizzes#new</h1>
<p>Find me in app/views/quizzes/new.html.erb</p>
 -->
<div class="login">
 <%= form_for @quiz do |f| %>
  <% if @quiz.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @quiz.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  
    <%= f.text_field :title, placeholder: 'Title' %>
    <div id="select"><%= f.select(:category, {"Sport" => "Sport", "Romance" => "Romance", "Education" => "Education", "Religion" => "Religion"})%>
    <%= f.hidden_field :user_id, value: session[:user_id] %>


    <%= f.hidden_field :user_id, value: session[:user_id] %>
  </div>

  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>
<div class="shadow"></div>

app/views/sesions/new.html.erb
<%= link_to('Back to home',{controller: 'quizzes', action: 'index'}, id: "homepage" )%>
<div id= "pipe">|</div>
<%= link_to('Sign up',{controller: 'users', action: 'new'}, id: "homepage" )%>


<div class="login">
<%= form_tag sesions_path do %>
    <%= text_field_tag :email, params[:email], placeholder: 'email' %>
    <%= password_field_tag :password,params[:password], placeholder: 'password'%>
	<%= submit_tag(:login) %>
<% end %>
</div>
<div class="shadow"></div>

app/views/users/new.html.erb
<%= link_to('Back to home',{controller: 'quizzes', action: 'index'}, id: "homepage" )%>


<div class="login">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  
    <%= f.text_field :email, placeholder: 'Email' %>

   
    <%= f.password_field :password, placeholder: 'password' %>
 
    
    <%= f.password_field :password_confirmation, placeholder: 'Confirmation' %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>
<div class="shadow"></div>